spring:
    datasource:
        password: root
        username: root
        url: jdbc:mysql://localhost:3306/fornecedor?serverTimezone=America/Sao_Paulo&useSSL=false&allowPublicKeyRetrieval=true
    jpa:
        hibernate:
            ddl-auto: create

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
